// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCtINKElaJwCBo5weKfTnQ-D5ZZH4d3No',
    appId: '1:1049105076872:web:62129cc4638c99b68f053d',
    messagingSenderId: '1049105076872',
    projectId: 'stressed-out-72eaa',
    authDomain: 'stressed-out-72eaa.firebaseapp.com',
    databaseURL: 'https://stressed-out-72eaa-default-rtdb.firebaseio.com',
    storageBucket: 'stressed-out-72eaa.appspot.com',
    measurementId: 'G-D081CDPSFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPeZmt7rJa2muaZKfCWQVSZtoRNJlhkek',
    appId: '1:1049105076872:android:b798103294cbc6238f053d',
    messagingSenderId: '1049105076872',
    projectId: 'stressed-out-72eaa',
    databaseURL: 'https://stressed-out-72eaa-default-rtdb.firebaseio.com',
    storageBucket: 'stressed-out-72eaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpsccl_LWqWevZbv4KXy46IGj2vJO1qg',
    appId: '1:1049105076872:ios:eeff0655d64c6d7a8f053d',
    messagingSenderId: '1049105076872',
    projectId: 'stressed-out-72eaa',
    databaseURL: 'https://stressed-out-72eaa-default-rtdb.firebaseio.com',
    storageBucket: 'stressed-out-72eaa.appspot.com',
    iosClientId: '1049105076872-0qgso07oni27lv1j4r0f45go3kqjddj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.stressedOut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpsccl_LWqWevZbv4KXy46IGj2vJO1qg',
    appId: '1:1049105076872:ios:eeff0655d64c6d7a8f053d',
    messagingSenderId: '1049105076872',
    projectId: 'stressed-out-72eaa',
    databaseURL: 'https://stressed-out-72eaa-default-rtdb.firebaseio.com',
    storageBucket: 'stressed-out-72eaa.appspot.com',
    iosClientId: '1049105076872-0qgso07oni27lv1j4r0f45go3kqjddj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.stressedOut',
  );
}
