// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEE3t21OqCM3YUWJ2j6bjL6zOxj7CyRE4',
    appId: '1:891866348671:web:8ac4df104d687917ab534a',
    messagingSenderId: '891866348671',
    projectId: 'capstone-d2282',
    authDomain: 'capstone-d2282.firebaseapp.com',
    databaseURL: 'https://capstone-d2282-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-d2282.appspot.com',
    measurementId: 'G-M78D9WJJS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5p9lR3I7otbrNAxPZeMI_xcLOFapqt8g',
    appId: '1:891866348671:android:525da263c62fdf38ab534a',
    messagingSenderId: '891866348671',
    projectId: 'capstone-d2282',
    databaseURL: 'https://capstone-d2282-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-d2282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnk0QR4gpiOuXOuhSG-oDz1CUef0Qm6Qw',
    appId: '1:891866348671:ios:9383e1987145279dab534a',
    messagingSenderId: '891866348671',
    projectId: 'capstone-d2282',
    databaseURL: 'https://capstone-d2282-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-d2282.appspot.com',
    iosClientId: '891866348671-0d97lve47dci5dhekp00hhe7qlevj554.apps.googleusercontent.com',
    iosBundleId: 'com.example.stressedOut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnk0QR4gpiOuXOuhSG-oDz1CUef0Qm6Qw',
    appId: '1:891866348671:ios:9383e1987145279dab534a',
    messagingSenderId: '891866348671',
    projectId: 'capstone-d2282',
    databaseURL: 'https://capstone-d2282-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-d2282.appspot.com',
    iosClientId: '891866348671-0d97lve47dci5dhekp00hhe7qlevj554.apps.googleusercontent.com',
    iosBundleId: 'com.example.stressedOut',
  );
}
